// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: pk_ctrl.proto
#ifndef GRPC_pk_5fctrl_2eproto__INCLUDED
#define GRPC_pk_5fctrl_2eproto__INCLUDED

#include "pk_ctrl.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace pkcamera {

class PkCamera final {
 public:
  static constexpr char const* service_full_name() {
    return "pkcamera.PkCamera";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetCamStatus(::grpc::ClientContext* context, const ::pkcamera::Field& request, ::pkcamera::CamStatus* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pkcamera::CamStatus>> AsyncGetCamStatus(::grpc::ClientContext* context, const ::pkcamera::Field& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pkcamera::CamStatus>>(AsyncGetCamStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pkcamera::CamStatus>> PrepareAsyncGetCamStatus(::grpc::ClientContext* context, const ::pkcamera::Field& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pkcamera::CamStatus>>(PrepareAsyncGetCamStatusRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void GetCamStatus(::grpc::ClientContext* context, const ::pkcamera::Field* request, ::pkcamera::CamStatus* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pkcamera::CamStatus>* AsyncGetCamStatusRaw(::grpc::ClientContext* context, const ::pkcamera::Field& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pkcamera::CamStatus>* PrepareAsyncGetCamStatusRaw(::grpc::ClientContext* context, const ::pkcamera::Field& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetCamStatus(::grpc::ClientContext* context, const ::pkcamera::Field& request, ::pkcamera::CamStatus* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pkcamera::CamStatus>> AsyncGetCamStatus(::grpc::ClientContext* context, const ::pkcamera::Field& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pkcamera::CamStatus>>(AsyncGetCamStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pkcamera::CamStatus>> PrepareAsyncGetCamStatus(::grpc::ClientContext* context, const ::pkcamera::Field& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pkcamera::CamStatus>>(PrepareAsyncGetCamStatusRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void GetCamStatus(::grpc::ClientContext* context, const ::pkcamera::Field* request, ::pkcamera::CamStatus* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::pkcamera::CamStatus>* AsyncGetCamStatusRaw(::grpc::ClientContext* context, const ::pkcamera::Field& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pkcamera::CamStatus>* PrepareAsyncGetCamStatusRaw(::grpc::ClientContext* context, const ::pkcamera::Field& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetCamStatus_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetCamStatus(::grpc::ServerContext* context, const ::pkcamera::Field* request, ::pkcamera::CamStatus* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetCamStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_GetCamStatus() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetCamStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCamStatus(::grpc::ServerContext* context, const ::pkcamera::Field* request, ::pkcamera::CamStatus* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCamStatus(::grpc::ServerContext* context, ::pkcamera::Field* request, ::grpc::ServerAsyncResponseWriter< ::pkcamera::CamStatus>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetCamStatus<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetCamStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_GetCamStatus() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ExperimentalWithCallbackMethod_GetCamStatus<BaseClass>, ::pkcamera::Field, ::pkcamera::CamStatus>(
          [this](::grpc::ServerContext* context,
                 const ::pkcamera::Field* request,
                 ::pkcamera::CamStatus* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->GetCamStatus(context, request, response, controller);
                 }, this));
    }
    ~ExperimentalWithCallbackMethod_GetCamStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCamStatus(::grpc::ServerContext* context, const ::pkcamera::Field* request, ::pkcamera::CamStatus* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void GetCamStatus(::grpc::ServerContext* context, const ::pkcamera::Field* request, ::pkcamera::CamStatus* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_GetCamStatus<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetCamStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_GetCamStatus() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetCamStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCamStatus(::grpc::ServerContext* context, const ::pkcamera::Field* request, ::pkcamera::CamStatus* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetCamStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_GetCamStatus() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetCamStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCamStatus(::grpc::ServerContext* context, const ::pkcamera::Field* request, ::pkcamera::CamStatus* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCamStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetCamStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_GetCamStatus() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ExperimentalWithRawCallbackMethod_GetCamStatus<BaseClass>, ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->GetCamStatus(context, request, response, controller);
                 }, this));
    }
    ~ExperimentalWithRawCallbackMethod_GetCamStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCamStatus(::grpc::ServerContext* context, const ::pkcamera::Field* request, ::pkcamera::CamStatus* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void GetCamStatus(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetCamStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_GetCamStatus() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::pkcamera::Field, ::pkcamera::CamStatus>(std::bind(&WithStreamedUnaryMethod_GetCamStatus<BaseClass>::StreamedGetCamStatus, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_GetCamStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetCamStatus(::grpc::ServerContext* context, const ::pkcamera::Field* request, ::pkcamera::CamStatus* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetCamStatus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::pkcamera::Field,::pkcamera::CamStatus>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetCamStatus<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetCamStatus<Service > StreamedService;
};

}  // namespace pkcamera


#endif  // GRPC_pk_5fctrl_2eproto__INCLUDED
